services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # HOST here should match the service (mysql)
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=vetlog
      # Used by init.sql
      - DATABASE_USER=vetlog_user
      - DATABASE_PASSWORD=vetlog_password

    # volumes:
    #   # Mount test reports if needed
    #   - ../test-reports:/app/test-reports

  mysql:
    image: mysql:8.0
    environment:
      # MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vetlog
      # MYSQL_USER: test_user
      # MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
